/**
 * Единый набор иконок конструктора (lucide, штриховые, монохромные).
 *
 * Импортировать иконки только отсюда: так набор остаётся одинаковым по
 * толщине и стилю, а замена иконки делается в одном месте. Эмодзи в
 * интерфейсе не используем — они цветные и ломают вид панели.
 */
export {
  MousePointer2 as IconSelect,
  PenLine as IconDraw,
  Ruler as IconRuler,
  Triangle as IconMeasure,
  Undo2 as IconUndo,
  Redo2 as IconRedo,
  Shapes as IconNewShape,
  FlipHorizontal2 as IconMirror,
  Pentagon as IconContour,
  Trash2 as IconDelete,
  Grid3X3 as IconGrid,
  RulerDimensionLine as IconDimensions,
  TriangleDashed as IconTriangles,
  Magnet as IconSnap,
  Maximize2 as IconFit,
  Plus as IconPlus,
  Minus as IconMinus,
  HelpCircle as IconHelp,
  ChevronUp as IconChevronUp,
  ChevronDown as IconChevronDown,
  Check as IconCheck,
  CornerUpLeft as IconStepBack,
  X as IconClose,
  LayoutDashboard as IconDashboard,
  ClipboardList as IconOrders,
  Users as IconClients,
  Film as IconFilms,
  Palette as IconColors,
  Package as IconWarehouse,
  ShieldCheck as IconUsers,
  Layers as IconLogo,
  Power as IconLogout,
  RectangleHorizontal as IconRect,
  Circle as IconCircle,
  Spline as IconFreeform,
  Eye as IconShow,
  EyeOff as IconHide,
  Focus as IconIsolate,
  Files as IconProjects,
  FilePlus2 as IconProjectNew,
  Pencil as IconRename,
  Copy as IconCopy,
  PanelLeftClose as IconPanelClose,
  PanelLeftOpen as IconPanelOpen,
  CornerUpLeft as IconTurnLeft,
  CornerUpRight as IconTurnRight,
  ArrowRight as IconStraight,
  Wand2 as IconWizard,
  TriangleAlert as IconWarning,
  Clock3 as IconSaved,
  Settings as IconSettings,
  Download as IconUpdate,
} from 'lucide-vue-next'
